### ISSUE TITLE
Microformat description truncated

### ISSUE THREAD

**Issue by steros76** [MattMcFarland/SUq#12]
Microformat description seems to be truncated at about 260 characters.
Is it a known issue?

**Comment by MattMcFarland** [comment]
I think this was (perhaps under bad judgement) intentional (let me double check) to avoid long polling, we can definitely fix this!

**Comment by MattMcFarland** [comment]
Just to confirm it is and will be fixed.

**Comment by MattMcFarland** [comment]
fixed!
