### ISSUE TITLE
Running an image URL through this exceeds callback size

### ISSUE THREAD

**Issue by jdrydn** [MattMcFarland/SUq#13]
Evening,

In using this module, there are some strange behaviours when passing an image URL.

Given this:

``` js
suq(url, function (err) {
  if (err) throw err;
  else process.exit(0);
});
```

And this:
![This excellent GIF](http://66.media.tumblr.com/dc2dc193e49d92c60e28aed0fdee4f80/tumblr_nzxwxeoBUW1qlt8foo6_r1_250.gif)

```
http://66.media.tumblr.com/dc2dc193e49d92c60e28aed0fdee4f80/tumblr_nzxwxeoBUW1qlt8foo6_r1_250.gif
```

This happens:

```
RangeError: Maximum call stack size exceeded
  at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:35:18
  at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:25:5
  at Array.forEach (native)
  at walk (/super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:24:9)
  at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:27:7
  at Array.forEach (native)
  at walk (/super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:24:9)
  at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:27:7
  at Array.forEach (native)
  at walk (/super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:24:9)
```

---

Simple steps to reproduce -  Try it on the command line:

```
$ node
> var suq = require('suq');
undefined
> var callback = function (err) { if (err) throw err; else console.log('Finished!'); }
undefined
> var url = 'http://66.media.tumblr.com/dc2dc193e49d92c60e28aed0fdee4f80/tumblr_nzxwxeoBUW1qlt8foo6_r1_250.gif';
undefined
> suq(url, callback);
undefined
> RangeError: Maximum call stack size exceeded
    at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:35:18
    at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:25:5
    at Array.forEach (native)
    at walk (/super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:24:9)
    at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:27:7
    at Array.forEach (native)
    at walk (/super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:24:9)
    at /super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:27:7
    at Array.forEach (native)
    at walk (/super-amazing-project/node_modules/microdata-node/lib/microdataDom.js:24:9)
```

---

Potential solutions include:
- Checking the response from `request` is definitely a `text/html` response, and if not then exiting early:

``` js
if (res.headers['content-type'] !== 'text/html') {
  return callback(null, {});
}
```
- Expose the `cleanMicrodata` function (and the following "pyramid" callback) as it's own independent function, so a developer could pass their own HTML and the module would pick up where it left off:

``` js
var suq = require('suq');
var request = require('request');

request(opts, function (err, res, body) {
  if (err) return callback(err);
  else if (!res || !res.statusCode) return callback(new Error('No response'));
  else if (res.headers['content-type'] !== 'text/html') return callback();
  else suq.parse(body, callback);
});
```

Now, I've forked this because I don't mind implementing this, but rather than just implement one solution that is rejected because it "_changes how the module works_" etc. I'd rather run it past someone sensible (@MattMcFarland) first 😉

**Comment by MattMcFarland** [comment]
Thanks!  Are these two separate solutions? I am wondering what the use case for hitting urls that are not html??

**Comment by jdrydn** [comment]
Basically, in order to fetch data for a given URL I'm throwing the URL at `suq`, and I was about to write a check for `if EXT in LIST then EXIT EARLY` but then I realised that `LIST` is going to be massive. It makes sense that `suq` would hit the URL and if it wasn't HTML then it just exits early, rather than forcing each developer to implement their own checks?

**Comment by jdrydn** [comment]
> I am wondering what the use case for hitting urls that are not html??

Given this, I've implemented solution **2**, "_Expose the cleanMicrodata function (and the following "pyramid" callback) as it's own independent function, so a developer could pass their own HTML and the module would pick up where it left off_", because `suq` shouldn't have to care about the URL being thrown at it.

**Comment by MattMcFarland** [comment]
Thanks,  I updated and published.
