### ISSUE TITLE
Body undefined

### ISSUE THREAD

**Issue by outmost** [MattMcFarland/SUq#4]
Looks like the body callback is missing on line 62 of index.js, causes the generic.js recipe to error

https://github.com/MattMcFarland/SUq/blob/master/index.js#L62

Is this:

```
 callback(null, populate);
```

Should be this?

```
 callback(null, populate, body);
```

**Comment by MattMcFarland** [comment]
ahhh not sure i'll look at it!  I refactored it and didnt realize it broke the generic recipe. thanks for pointing this out.

**Comment by outmost** [comment]
Sorry, not sure that I was clear!

Without the change, body will always be undefined. 

I just mentioned the recipe as an example

**Comment by MattMcFarland** [comment]
Ahhh yes you are correct, as it would be null, populate, body now.  

Feel free to send a PR if you want, or I can work on this later this week.
