### ISSUE TITLE
Adding options for request()

### ISSUE THREAD

**Issue by garymoon** [MattMcFarland/SUq#7]
Hi Matt,

Thanks so much for SUq, it's saved me a ton of time.

I wanted to get your thoughts on allowing options to be passed to request. I recently ran into an issue where request hits the `EventEmitter.maxListeners` limit when it hits its internal `maxRedirects` limit, and a warning is printed:

```
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
```

The workaround would be to either increase `maxListeners` by 1, or decrease `maxRedirects` by 1. However, the solution (at least in this particular case) would be to add a cookie jar to request to prevent the infinite loop.

You can reproduce this issue by attempting to SUq any NYTimes article that attempts to redirect you to the paywall. Without a cookie jar (request's default) you end up in an infinite redirect loop. 

```
http://www.nytimes.com/2016/01/31/books/review/the-powers-that-were.html 
```

I can see in `parse()` there was a third `opts` parameter, but it isn't used. I would propose permitting users to specify request options in that object, and merge them with any defaults SUq would care to introduce. Something along the lines of this at [index.js line 47](https://github.com/MattMcFarland/SUq/blob/master/index.js#L47):

```
var parse = function(url, callback, opts) {

  var req_opts = _({}).extend({"url": url}, opts)

  loadDocument(req_opts, function (err, body, $,  res) {
```

The user-specified options would then be passed as the first argument to `request()` in `loadDocument()`. Alternatively a property on the opts object could be reserved for request, or a fourth parameter added. I'd be happy to provide a PR once I have your thoughts.

Thanks again,
Gary.

**Comment by MattMcFarland** [comment]
Hi Gary, glad you are digging suq! I think options are fine as long as they
are.. well.. optional. :D - If we can add it in such a way that it doesn't
break previous functionality and can be omitted then I think it would be a
good addition especially with some edge cases. If this sounds good to you
feel free to send a PR.

Best,
Matt

**Comment by garymoon** [comment]
Hi Matt,

I've opened PR #8. Please let me know if anything isn't to your liking.

Cheers,
Gary.

**Comment by MattMcFarland** [comment]
Wow that was fast.  I don't have time today to look over it without a quick glance.  The quick glance test is passing, but I'll have to take a closer look at it tomorrow, thanks again!  :)

**Comment by garymoon** [comment]
No problem :) Thanks Matt.

**Comment by MattMcFarland** [comment]
Can you update the readme, add an example to the recipes folder, and add your details to contributors list in package json (update package json version as well) - then I'll merge and update the package.  

Thanks!

**Comment by garymoon** [comment]
Hi Matt,

All done in PR #10.

Cheers,
Gary.
